### ISSUE TITLE
Can't seem to run program. Missing Module?

### ISSUE THREAD

**Issue by fiveseven808** [willdeberry/bjarkan#3]
On program call:

```
Traceback (most recent call last):
  File "/usr/local/bin/bjarkan", line 7, in <module>
    from bjarkan.bjarkan import main
  File "/usr/local/lib/python2.7/dist-packages/bjarkan/__init__.py", line 4, in <module>
    import bjarkan
  File "/usr/local/lib/python2.7/dist-packages/bjarkan/bjarkan.py", line 8, in <module>
    from bjarkan.connection_manager import *
ImportError: No module named connection_manager

```

I'm guessing it may be a python 2 vs python 3 thing? No idea how to troubleshoot this.

**Comment by fiveseven808** [comment]
seems to import into python3 just fine, but i'm not 100% sure how to use it

**Comment by willdeberry** [comment]
Yes, this was written with only python3 in mind.

Once installed, should be as easy as a couple commands
`bjarken scan`
This will provide you a list of devices to connect to.
`bjarken pair -d <address of device>`
This will attempt to connect to the device provided.


Sorry it took me a bit to get back to this, life happens. Let me know if you need any additional help.
